import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.generated.ts');

const raw = process.env.API_URL?.trim();
const onVercel = Boolean(process.env.VERCEL);

if (!raw) {
  if (onVercel) {
    console.error('Missing API_URL for Vercel build. Set it in Vercel → Project → Settings → Environment Variables.');
    process.exit(1);
  }
}

const fallback = 'http://localhost:3000';
const apiUrl = (raw && raw.length > 0 ? raw : fallback).replace(/\/+$/, '');

const contents = `// Generated by scripts/write-api-env.mjs — do not edit by hand.
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(apiUrl)},
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, contents, 'utf8');
